### ISSUE TITLE
flakiness: "should distribute bootstrap rewards to validators in committee"

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-ethereum-contracts-v2#82]
should distribute bootstrap rewards to validators in committee

https://circleci.com/gh/orbs-network/orbs-ethereum-contracts-v2/261

**Comment by ronnno** [comment]
another instance:
https://circleci.com/gh/orbs-network/orbs-ethereum-contracts-v2/298?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

---
```
 1) bootstrap-rewards-level-flows
       should distribute bootstrap rewards to validators in committee:

      AssertionError: expected '120000004000000000000000' to equal '120000003000000000000000'
      + expected - actual

      -120000004000000000000000
      +120000003000000000000000
      
      at /root/project/test/bootstrap-rewards.spec.ts:91:48
      at step (/root/project/test/bootstrap-rewards.spec.ts:33:23)
      at Object.next (/root/project/test/bootstrap-rewards.spec.ts:14:53)
      at fulfilled (/root/project/test/bootstrap-rewards.spec.ts:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

```
